services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_HOST=192.168.208.49
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://192.168.208.49:5678/
      - GENERIC_TIMEZONE=UTC
      - WAZUH_API_URL=${WAZUH_API_URL}
      - WAZUH_API_USER=${WAZUH_API_USER}
      - WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD}
      - N8N_PUBLIC_API_DISABLED=false
      - N8N_PUBLIC_API_SWAGGERUI_DISABLED=false
    volumes:
      - ./n8n-data:/home/node/.n8n
    networks:
      - n8n-network
    depends_on:
      - ollama
      - foundation-sec

  foundation-sec:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./scripts/foundation_sec_api_lite.py:/app/foundation_sec_api_lite.py
      - ./requirements-foundation.txt:/app/requirements-foundation.txt
    command: bash -c "pip install -r requirements-foundation.txt && python foundation_sec_api_lite.py"
    container_name: foundation-sec-8b
    restart: always
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://foundation-sec-ai:11434
      - AI_PROVIDER=ollama # set to 'deepseek' to route to DeepSeek API
      - DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  ollama:
    image: ollama/ollama:latest
    container_name: foundation-sec-ai
    restart: always
    ports:
      - "11434:11434"
    mem_limit: 12g
    memswap_limit: 12g
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
      - OLLAMA_ORIGINS=http://localhost:5678,http://localhost:3000
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
    driver: local
  foundation_sec_cache:
    driver: local

networks:
  n8n-network:
    driver: bridge
